### ISSUE TITLE
bambang

### ISSUE THREAD

**Issue by hackred123** [princerayz/SpoonTools#2]
gak bisa cara run ini hehe
bisa bantu gak bang

**Comment by princerayz** [comment]
Apanya gk bisa run,
Kamu build pakai visual studio 2015++

Syarat .net 2015.

**Comment by tarokay** [comment]
Bang cara dapetin botnya gmana,ko eror mulu

**Comment by princerayz** [comment]
Ya buat pakai nomorhp, dan password
Lihat screenshoot
Format: NoHP,Password
Contoh : 0812345778,1234567

**Comment by tarokay** [comment]
Jd botnya cma 1 aja bang? Maaf ada ig ga biar chatnya enak

**Comment by princerayz** [comment]
Ya botnya bisa banyak, tergantung kamu buat berapa.

Save aja per line user+passnya di notepad

User1,pw1
User2,pw2
User3,pw3

**Comment by tarokay** [comment]
Ok suhu,sya cba dlu

**Comment by tarokay** [comment]
Remote servet returned an error :(403) tu gimana bng?

**Comment by tarokay** [comment]
Saya pake visual 2019 apa karna itu y

**Comment by princerayz** [comment]
Otak atik user-agent nya

**Comment by tarokay** [comment]
User agen yg mna bng,Ada kontak g bng ,kaya ig misalnya biar bs kirim gambar.. nub sya bng

**Comment by princerayz** [comment]
Ini tools open source, coba diotak atik lagi.
Cari aja user-agent.
Ini halaman bukan untuk issue begini, saya close comment ya

**Comment by hackred123** [comment]
UDAH KELAR BANG RAY 😊

Pada tanggal Sen, 30 Sep 2019 04.12, Prince Ray <notifications@github.com>
menulis:

**Comment by bimoli** [comment]
Bang cara buat script bot nya gimana
